
windows-winpcap:
  tags:
  - shared-windows
  script:
  - choco install -y winpcap
  - "C:\\Program Files\\Git\\bin\\bash" scripts/test.sh --filter "TestCategory!=Timestamp"

ubuntu-20.04:
  image: mcr.microsoft.com/dotnet/sdk:3.1-focal
  script:
  - sudo -E bash scripts/install-libpcap.sh
  - sudo -E bash scripts/test.sh

ubuntu-20.04-arm64:
  image: mcr.microsoft.com/dotnet/sdk:3.1-focal-arm64v8
  script:
  - sudo -E bash scripts/install-libpcap.sh
  - sudo -E bash scripts/test.sh
