
default:
  artifacts:
    reports:
      junit: Test/TestResults/TestResults.xml

windows-winpcap:
  tags:
  - shared-windows
  script:
  - choco install -y winpcap
  - choco install -y netfx-4.8-devpack
  - choco install -y dotnet-sdk
  # No bash support
  - dotnet test --logger:junit --test-adapter-path:. --filter "TestCategory!=Timestamp"
  # No code coverage yet, it has to be done after the tokens are configured

ubuntu-20.04:
  image: mcr.microsoft.com/dotnet/sdk:5.0-focal
  script:
  - apt-get update
  - apt-get install -y build-essential
  - bash scripts/install-libpcap.sh
  - bash scripts/test.sh
