
dotnet-winpcap:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
  - choco install -y winpcap
  - bash scripts/test.sh --filter "TestCategory!=Timestamp"

framework-winpcap:
  image: mcr.microsoft.com/dotnet/framework/sdk
  script:
  - choco install -y winpcap
  - bash scripts/test.sh --filter "TestCategory!=Timestamp"
