#!/bin/bash

# script to generate release files
# parameter 1 is the output directory
# parameter 2 is the 'from' version being released
# parameter 3 is the 'to' version being released

function PrintUsage()
{
  echo "example:";
  echo "  ./build_release ~/release_dir 2.0.0 2.1.0";
}

if [ "$#" -ne 3 ]; then
  PrintUsage
  exit
fi

echo "Generating release notes"
./generate_release_notes $1 $2 $3

echo "make_bin_release"
./make_bin_release $1 $3

echo "make_src_release"
./make_src_release $1 $3
