# Copyright 2020-2021 Ayoub Kaanich <kayoub5@live.com>
# SPDX-License-Identifier: MIT

codecov:
  # Allow collecting coverage even if some CIs fail
  require_ci_to_pass: false
  notify:
    # 4 for appveyor
    # 3 for azure pipelines
    # 1 for circleci
    # Total = 8
    # Tolerate one of the services being down (worst case appveyor)
    after_n_builds: 4
