#!/bin/bash

source Common

# script to help with building a source release package
#
# parameter 1 is the output directory
# parameter 2 is the version being released
#

function PrintUsage()
{
  echo "usage:";
  echo "  ./make_src_release OutputDirectory VersionNumber TagName";
  echo "";
  echo "example:";
  echo "  ./make_src_release ~/sharppcap_releases 2.0.0";
}

if [ "$#" -ne 2 ]; then
  PrintUsage
  exit
fi

echo "make_src_release $1 $2"

baseOutputDirectory=$1
releaseVersion=$2
gitRemotePublicPath=git://sharppcap.git.sourceforge.net/gitroot/sharppcap/sharppcap

# setup some variables
baseOutputDirectory=${baseOutputDirectory}/src
mkdir -p ${baseOutputDirectory}
outputName=SharpPcap-${releaseVersion}

# build the tag by converting the '.' in the version to '_'
tag=SharpPcap_${2//./_}

# create a zip file of the appropriate tag
git archive --format=zip --remote=${gitRemotePublicPath} $tag > ${baseOutputDirectory}/${outputName}.src.zip

